DATA_PATH = "./data/data_cross_ccf_rmsd.csv"       # Замените на путь к новым данным
SVD_MODEL_PATH = "models/svd_model.joblib"
PARAMS_PATH = "models/best_params.json"         # Параметры, полученные после Optuna
OBJECTIVE = 'rank:ndcg'
METRIC = 'ndcg@1'  # currently only single-metric evaluation is implemented
N_TRIALS = 2  # number of Optuna trials to find good hyperparameters
N_ESTIMATORS = 1000  # maximum number of boosting iterations
EARLY_STOPPING_ROUNDS = 20  # stop if the metric doesn't improve for 20 consecutive rounds
LEARNING_RATE_RANGE = (0.01, 0.15)
MAX_DEPTH_RANGE = (3, 6)
MIN_CHILD_WEIGHT = (2, 10)
GAMMA_RANGE = (0, 5)
SUBSAMPLE_RANGE = (0.6, 0.8)
COLSAMPLE_BYTREE = (0.6, 0.8)  # fraction of features randomly selected for each tree
SEED = 2007
TOP_K = 3  # number of top-performing Optuna trials for which learning curves will be shown on train and validation sets
